apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fds7sycfs-nodejs 
  janus-idp.io/tekton: fds7sycfs-nodejs
  backstage.io/kubernetes-id: fds7sycfs-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fds7sycfs-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  